# Generated by Django 3.0.5 on 2020-06-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200602_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='launch_date',
            new_name='Launch_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_desc',
            new_name='Product_desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='Product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_price',
            field=models.IntegerField(default=0),
        ),
    ]
