# Generated by Django 3.0.5 on 2020-06-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200609_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_subcategory',
            field=models.CharField(default='', max_length=20),
        ),
    ]
