# Generated by Django 3.0.5 on 2020-06-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=20)),
                ('L_name', models.CharField(max_length=300)),
                ('Email', models.CharField(default='', max_length=20)),
                ('Message', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
